version: '3'

services:

  nginx:
    build:
      context: nginx
    ports:
      - "8000:80"
    links:
      - node
    networks:
      - node-networks

  node:
    build:
      context: node
      dockerfile: Dockerfile.prod
    container_name: node
    entrypoint: dockerize --wait tcp://db:3306 -timeout 30s ./.docker/entrypoint.sh
    # command: node index.js
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    # ports:
    #   - "3000:3000"
    depends_on:
      - db
    networks:
      - node-networks

  db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        - node-networks
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root

networks:
  node-networks:
    driver: bridge